networks:
  servarrnetwork:
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:

  rutorrent:
    image: ghcr.io/linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/rutorrent/config:/config
      - /video:/downloads
    ports:
      - 80:80
      - 5000:5000
      - 51413:51413
      - 2881:2881/udp
    restart: always
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.10

  medusa:
    image: pymedusa/medusa
    container_name: medusa
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/medusa:/config
      - /home/craig/data/downloads/medusa:/downloads
      - /home/craig/data/tv:/tv
    ports:
      - 8081:8081
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.11

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/sabnzbd:/config
      - /video:/video #optional
      - /home/craig/data/downloads/sabnzbd:/incomplete-downloads #optional
    ports:
      - 8282:8282
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.13  
    restart: always

  tautullisingaplex:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautullisingaplex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/tautullisinga/config:/config
    ports:
      - 8181:8181
    restart: always
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.14

  tautulliwileyplex:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulliwileyplex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/tautulliwiley/config:/config
    ports:
      - 8182:8182
    restart: always
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.15
