networks:
  servarrnetwork:
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      - WEBUI_PORT=8080
      - TORRENTING_PORT=2881
    volumes:
      - /docker/qbittorrent:/config
      - /home/craig/data:/data
      - /video:/video
    healthcheck:
        test: ping -c 1 1.1.1.1 || exit 1
        interval: 60s
        retries: 3
        start_period: 20s
        timeout: 10s
    ports:
      - 2881:2881
      - 8080:8080
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.9

  medusa:
    image: pymedusa/medusa
    container_name: medusa
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/medusa:/config
      - /home/craig/data/downloads/medusa:/downloads
      - /home/craig/data/tv:/tv
    ports:
      - 8081:8081
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.11

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/sabnzbd:/config
      - /video:/video #optional
      - /home/craig/data/downloads/sabnzbd:/incomplete-downloads #optional
    ports:
      - 8282:8282
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.13  
    restart: unless-stopped

  tautullisingaplex:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautullisingaplex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/tautullisinga/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.14

  tautulliwileyplex:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulliwileyplex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - /docker/tautulliwiley/config:/config
    ports:
      - 8182:8182
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.15
