services:
      
  mariadb:
      image: mariadb
      environment:
       - MYSQL_ROOT_PASSWORD=12georgia
       - MYSQL_DATABASE=wordpress
      volumes:
       - /docker/scrsc_wordpress/db:/var/lib/mysql
      restart: always

  wordpress:
      image: wordpress
      links:
       - mariadb:mysql
      environment:
       - WORDPRESS_DB_PASSWORD=12georgia
       - WORDPRESS_DB_USER=root
      ports:
       - 85:80
      volumes:
       - /docker/scrsc_wordpress/html:/var/www/html
      depends_on:
       - mariadb
      restart: always
      healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 30s
            timeout: 10s
            retries: 5
