services:
    mariadb:
      image: mariadb
      environment:
       - MYSQL_ROOT_PASSWORD=12georgia
       - MYSQL_DATABASE=wordpress
      volumes:
       - /docker/wordpress/db:/var/lib/mysql
      restart: always

    wordpress:
      image: wordpress
      links:
       - mariadb:mysql
      environment:
       - WORDPRESS_DB_PASSWORD=12georgia
       - WORDPRESS_DB_USER=root
      ports:
       - 84:80
      volumes:
       - /docker/wordpress/html:/var/www/html
      restart: always
      depends_on:
       - mariadb
      healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 30s
            timeout: 10s
            retries: 5
